# This notebook will be mainly used for the capstone project

<h1>Table of contents</h1>

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ol>
        <li><a href="#Conclusion">Conclusion - conclude the report</a></li>
        <li><a href="#Introduction">Introduction - discuss the business problem and who would be interested in this project</a></li>
        <li><a href="#Data">Data - describe the data that will be used to solve the problem and the source of the data</a></li>
        <li><a href="#Methodology">Methodology - discuss and describe any exploratory data analysis, any inferential statistical testing performed, and what machine learnings were used and why</a></li>
        <li><a href="#setting_up_tree">Setting up the Decision Tree</a></li>
        <li><a href="#Prediction">Prediction - Using the model to prodict the outcome</a></li>
        <li><a href="#Results">Results - discuss the results</a></li>
        <li><a href="#modeling">Discussion - discuss any observations noted and any recommendations that can be made based on the results</a></li>
    </ol>
</div>
<br>
<hr>

In [1]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [2]:
print ('Hello Capstone Project Course')

Hello Capstone Project Course


<hr>

<div id="Conclusion">
    <h2>Conclusion</h2>
</div>

In conclusion, based on the work done below, the data set cannot tell us the the possibility of getting into a car accident, but can tell us that if we are in an accident in certain conditions how severe it would be.

The decision tree model works 100% of the time on the test data after being trained. 

<hr>

<div id="Introduction">
        <h2>Introduction</h2>
</div>

# Discussion of the background:

To complete capstone, I will be working on a case study which is to predict the severity of an accident. 

Say you are driving to another city for work or to visit some friends. It is rainy and windy, and on the way, you come across a terrible traffic jam on the other side of the highway. Long lines of cars barely moving. As you keep driving, police car start appearing from afar shutting down the highway. Oh, it is an accident and there's a helicopter transporting the ones involved in the crash to the nearest hospital. They must be in critical condition for all of this to be happening.

# Problem:
Now, wouldn't it be great if there is something in place that could warn you, given the weather and the road conditions about the possibility of you getting into a car accident and how severe it would be, so that you would drive more carefully or even change your travel if you are able to. Well, this is exactly what you will be working on in this course.

<hr>

<div id="Data">
        <h2>Data</h2>
</div>

<div id="Description of Data">
        <h2>Description of Data</h2>

We will be using our shared data for Seattle city as an example of how to deal with the accidents data. 

The first column is the labeled data. The remaining columns have different types of attributes. Some or all can be used to train the model.

The label for the data set is severity, which describes the fatality of an accident. The shared data has unbalanced labels. The data will be balanced, otherwise, you will create a biased ML model. We can do some feature engineering to improve the predictability of the model.

# Attributes: 
In total there are 37 attributes (columns). Some attribtes have misisng data, and includes both numerical and categorical types of data. Attributes inlcude Location, Weather condition, Car speeding, Light conditions, Road condition, Junction junction, number of people involved, number of vehicles involed. 

Severity key 1 = Property Damage Only Collision    (136485 collisions)
Severity key 2 = Injury Collision                   (58188 collisions)



<hr>

<div id="Methodology">
        <h2>Methodology</h2>
</div>

The problem states that the road conditions and weather should be categories that indicate whether there is likelihood of getting into a car accident.

I have decided to use a **decision tree** because, looking at the categories, the weather and road conditions will effectively point to a damage only collision, or an injury collision. If a decision tree does not produce a high enough accuracy, I will try another method.

I will **clean the data** removing any blank or Unknown values from the Weather and Road Conditions columns.

In [60]:
#downlaod collision data
df = pd.read_csv ("https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv")

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  ... ROADCOND                LIGHTCOND  \
0  Matched  Intersection  37475.0  ...      Wet                 Daylight   
1  Matched         Block      NaN  ...      Wet  Dark - Street Lights On   
2  Matched         Block      NaN  ...      Dry                 Daylight   
3  Matched         Block      NaN  ...      Dry                 Daylight   
4  Matched  Intersection  34387.0  ...      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0           NaN         NaN      NaN         10   
1           NaN   6354039.0      NaN         11   
2           NaN   4323031.0      NaN         32   
3           NaN         NaN      NaN         23   
4           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

<div id="visualization_analysis">
    <h2>Data Visualization and Analysis</h2> 
</div>

#### Let’s see how many of each Severity is in our data set

In [5]:
df['SEVERITYCODE']

0         2
1         1
2         1
3         1
4         2
         ..
194668    2
194669    1
194670    2
194671    2
194672    1
Name: SEVERITYCODE, Length: 194673, dtype: int64

In [6]:
df.columns

Index(['SEVERITYCODE', 'X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO',
       'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
       'EXCEPTRSNDESC', 'SEVERITYCODE.1', 'SEVERITYDESC', 'COLLISIONTYPE',
       'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE',
       'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE', 'SDOT_COLDESC',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SDOTCOLNUM', 'SPEEDING', 'ST_COLCODE', 'ST_COLDESC',
       'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR'],
      dtype='object')

In [8]:
#I can see we have some 'Unkown' data here, and in the ROADCOND column too. Let's remove that 
df['WEATHER'].value_counts()

Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [22]:
# create df for our prediction, calling this data frame accident - dfacc
dfacc = df[['SEVERITYCODE', 'WEATHER', 'ROADCOND']]
dfacc

SEVERITYCODE   WEATHER ROADCOND
0                  2  Overcast      Wet
1                  1   Raining      Wet
2                  1  Overcast      Dry
3                  1     Clear      Dry
4                  2   Raining      Wet
...              ...       ...      ...
194668             2     Clear      Dry
194669             1   Raining      Wet
194670             2     Clear      Dry
194671             2     Clear      Dry
194672             1     Clear      Wet

[194673 rows x 3 columns]

## I want to see where we have null values, then remove them

Below we can see that we have null values in WEATHER and READCOND columns

In [23]:
missing_data = dfacc.isnull()
missing_data.head(10)

for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

SEVERITYCODE
False    194673
Name: SEVERITYCODE, dtype: int64

WEATHER
False    189592
True       5081
Name: WEATHER, dtype: int64

ROADCOND
False    189661
True       5012
Name: ROADCOND, dtype: int64



In [25]:
dfacc.dropna(subset=["WEATHER"], axis=0, inplace=True)
dfacc.dropna(subset=["ROADCOND"], axis=0, inplace=True)

missing_data = dfacc.isnull()
missing_data.head(10)

for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

SEVERITYCODE
False    173006
Name: SEVERITYCODE, dtype: int64

WEATHER
False    173006
Name: WEATHER, dtype: int64

ROADCOND
False    173006
Name: ROADCOND, dtype: int64



## We now have data without any null values and any 'Unkown' values

In [26]:
dfacc.dtypes

SEVERITYCODE     int64
WEATHER         object
ROADCOND        object
dtype: object

In [27]:
dfacc.head(100)

SEVERITYCODE   WEATHER ROADCOND
0               2  Overcast      Wet
1               1   Raining      Wet
2               1  Overcast      Dry
3               1     Clear      Dry
4               2   Raining      Wet
..            ...       ...      ...
106             1     Clear      Dry
109             1     Clear      Dry
110             1     Clear      Dry
111             1  Overcast      Dry
112             1  Overcast      Dry

[100 rows x 3 columns]

In [44]:
X = dfacc[['SEVERITYCODE', 'WEATHER', 'ROADCOND']].values
X[0:5]

array([[2, 'Overcast', 'Wet'],
       [1, 'Raining', 'Wet'],
       [1, 'Overcast', 'Dry'],
       [1, 'Clear', 'Dry'],
       [2, 'Raining', 'Wet']], dtype=object)

Some features in this dataset are categorical such as **WEATHER** or **ROADCOUNT**. Sklearn Decision Trees do not handle categorical variables. But still we can convert these features to numerical values.

In [46]:
from sklearn import preprocessing
le_WEATHER = preprocessing.LabelEncoder()
le_WEATHER.fit(['Clear','Raining','Overcast','Snowing','Fog/Smog/Smoke','Other','Sleet/Hail/Freezing Rain','Blowing Sand/Dirt','Severe Crosswind','Partly Cloudy'])
X[:,1] = le_WEATHER.transform(X[:,1]) 

le_ROADCOND = preprocessing.LabelEncoder()
le_ROADCOND.fit([ 'Dry', 'Wet', 'Ice', 'Snow/Slush','Other','Standing Water','Sand/Mud/Dirt','Oil'])
X[:,2] = le_ROADCOND.transform(X[:,2])

X[0:5]

array([[2, 4, 7],
       [1, 6, 7],
       [1, 4, 0],
       [1, 1, 0],
       [2, 6, 7]], dtype=object)

In [47]:
y = dfacc["SEVERITYCODE"]
y[0:5]

0    2
1    1
2    1
3    1
4    2
Name: SEVERITYCODE, dtype: int64

<hr>

<div id="setting_up_tree">
    <h2>Setting up the Decision Tree</h2>
    We will be using <b>train/test split</b> on our <b>decision tree</b>. Let's import <b>train_test_split</b> from <b>sklearn.cross_validation</b>.
</div>

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

<h3>Practice</h3>
Print the shape of X_trainset and y_trainset. Ensure that the dimensions match

In [51]:
print ('Train set:', X_trainset.shape,  y_trainset.shape)

Train set: (121104, 3) (121104,)


In [52]:
print ('Test set:', X_testset.shape,  y_testset.shape)

Test set: (51902, 3) (51902,)


<hr>

<div id="modeling">
    <h2>Modeling</h2>
    We will first create an instance of the <b>DecisionTreeClassifier</b> called <b>drugTree</b>.<br>
    Inside of the classifier, specify <i> criterion="entropy" </i> so we can see the information gain of each node.
</div>

In [53]:
from sklearn.tree import DecisionTreeClassifier

accTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
accTree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [54]:
accTree.fit(X_trainset,y_trainset)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

<hr>

<div id="Prediction">
    <h2>Prediction</h2>
    Let's make some <b>predictions</b> on the testing dataset and store it into a variable called <b>predaccTree</b>.
</div>


In [55]:
predaccTree = accTree.predict(X_testset)

In [56]:
print (predaccTree [0:5])
print (y_testset [0:5])

[1 1 2 1 1]
122146    1
144594    1
11905     2
105489    1
51948     1
Name: SEVERITYCODE, dtype: int64


<hr>

<div id="Results">
    <h2>Results</h2>
</div>


When we test the model, we see that it accurately predicts the possibility of an accident 100% of the time

In [57]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predaccTree))

DecisionTrees's Accuracy:  1.0


<hr>

<div id="Discussion">
    <h2>Discussion</h2>
</div>


The problem with the data is that it only tells us of those journeys where there was an accident. It does not help tell us whether a journey will definitely result in an accident or not. 